FROM node:20.11.0

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate

# Create base directories
WORKDIR /app
RUN mkdir -p /app/packages/client /app/packages/server

# Copy root package files
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

# Copy client files
COPY packages/client/package.json /app/packages/client/
COPY packages/client/vite.config.ts /app/packages/client/
COPY packages/client/index.html /app/packages/client/
COPY packages/client/src /app/packages/client/src/
COPY packages/client/tsconfig.json /app/packages/client/

# Copy server files
COPY packages/server/package.json /app/packages/server/
COPY packages/server/prisma /app/packages/server/prisma/
COPY packages/server/src /app/packages/server/src/
COPY packages/server/tsconfig.json /app/packages/server/
COPY packages/server/index.ts /app/packages/server/

# Copy shared configuration
COPY tsconfig.base.json /app/

# Install dependencies
RUN pnpm install --shamefully-hoist

# Generate Prisma client
RUN cd /app/packages/server && npx prisma generate --schema=./prisma/schema.prisma
